### ISSUE TITLE
Config for port:protocol paris

### ISSUE THREAD

**Issue by benbro** [jakehilton/netconnectionsmart#4]
Hi,

Is it possible to define port:protocol pairs?
For example if I only want to try:
RTMP on port 1935
RTMPS on port 443
RTMPT on port 80
I'll use something like:

```
["rtmp", 1935, "rtmps", 443, "rtmpt", 80];
```

It's not clear what order of port/protocols are tried when using:

```
nc.portArray = [1935,443,80];
```

The secure flag is not documented
https://github.com/jakehilton/netconnectionsmart/blob/master/src/com/gearsandcogs/utils/NetConnectionSmart.as#L132

There is a warning saying that secure connections cannot run over rtmpt.
Isn't it just RTMPTS? Same as RTMPT just over https instead of http?
https://github.com/jakehilton/netconnectionsmart/blob/master/src/com/gearsandcogs/utils/NetConnectionSmart.as#L442

Wrong type?
@see flash.net.NetConnection.proxyType
https://github.com/jakehilton/netconnectionsmart/blob/master/src/com/gearsandcogs/utils/NetConnectionSmart.as#L267

Thanks

**Comment by jakehilton** [comment]
Ben,
There is an internal port tester built into the net connection smart class which should test those protocols for you.

Here is a bit of code you can run to see this in action:

```
nc = new NetConnectionSmart();
nc.port_test = true;
nc.addEventListener(NetStatusEvent.NET_STATUS, handleNetStatus);

private function handleNetStatus(e:NetStatusEvent):void
        {
        switch (e.info.code)
                {
            case NetConnectionSmart.NETCONNECTION_PORT_TEST_UPDATE:

        var currConnection:PortConnection = e.info.internalTarget as PortConnection;
                    var currType:NetConnectionType = (e.target as NetConnectionSmart).netConnections[currConnection.id];

                    var status_output:String = "";
                    if (currConnection && currConnection.status && currConnection.status.info.code && currConnection.status.info.code != "")
                    {
                        var status_input:String = currConnection.was_connected ? NetConnectionSmart.NETCONNECTION_CONNECT_SUCCESS : currConnection.status.info.code;

                        var proxy_add:String = currConnection.proxyType;
                        status_output = status_input.split('NetConnection.Connect.')[1] + " proxy type ";
                        if (currConnection.was_connected)
                                proxy_add = currConnection.connectedProxyType;

                        status_output += proxy_add;

            trace(currType.full_protocol.toUpperCase() + " port " + String(currType.port) + " " + status_output);
                    }
    }
}
```

So it will run a port test as the net connection is configured.. so if you’d like it to test a few different options (rtmp vs rtmps) then instantiating multiple net connections would be recommended.

The output would look like this:

[trace] connecting...
[trace] NetConnection.PortTest.Update
[trace] RTMP port 443 Failed proxy type none
[trace] NetConnection.PortTest.Update
[trace] RTMP port 80 Failed proxy type none
[trace] NetConnection.PortTest.Update
[trace] RTMP port 1935 Success proxy type none
[trace] NetConnection.PortTest.Update
[trace] RTMP port 443 Failed proxy type CONNECTonly
[trace] NetConnection.PortTest.Update
[trace] RTMP port 80 Failed proxy type CONNECTonly
[trace] NetConnection.PortTest.Update
[trace] RTMP port 1935 Failed proxy type CONNECTonly
[trace] NetConnection.PortTest.Complete
[trace] we're done

This latest code requires 1.7.1 as I added the internalTarget to the NetStatusEvent in that version.
