### ISSUE TITLE
Invoke close POST request when using RTMPT

### ISSUE THREAD

**Issue by softforge** [jakehilton/netconnectionsmart#5]
I am streaming from a user's webcam to an RTMP server using netconnectionsmart. When using RTMPT, the stream data is posted correctly and all the data is received correctly at the server. However, after the data has finished being sent, the posts go back to calling idle and I never see the close post so the connection is never shut down and the server waits for more data before eventually timing out.

I may have implemented this incorrectly but I think I am calling close in the right way as it works fine using RTMP. Is there any way to manually invoke the close post when using RTMPT? Or can you give an example that correctly uses the library to stream and then close down the RTMPT session?

Many thanks.

**Comment by jakehilton** [comment]
So just to clarify.. are you seeing the client code disconnect right away but the server side isn’t recognizing the disconnect right away?

RTMPT operates under a polling mechanism. The client polls to the server at a set interval. The server may believe the client to be alive after is has disconnected until it times out after not receiving client messages for a certain amount of time. RTMP is a socket based protocol so when it disconnects the server knows immediately that it is disconnected.

As far as closing the net connection client side, there is no difference between rtmp and rtmpt methodologies in the way you should call it.

Have I correctly understood what you’re experiencing?

Thanks!

**Comment by softforge** [comment]
Thanks for you response. I'm not seeing the client code disconnecting or trying to disconnect at all when using RTMPT, the connection never gets closed (apart from when it eventually times out). With RTMP, it disconnects fine.

From reading the RTMPT spec, it looks like the client should sent a "close" POST that looks something like this:

...
POST /send/YXF4WTFMN8TCM/1394
POST /send/YXF4WTFMN8TCM/1395
POST /close/YXF4WTFMN8TCM/1396

But what I actually see is this:

...
POST /send/YXF4WTFMN8TCM/1394
POST /send/YXF4WTFMN8TCM/1395
POST /idle/YXF4WTFMN8TCM/1396
POST /idle/YXF4WTFMN8TCM/1397
...

The server is setup to do a load of post-processing when the connection is closed which works fine when using RTMP but never gets kicked off when using RTMPT. I'm not sure if my implementation is wrong or if the library is not closing when it should when using RTMPT.

Thanks for you help.

**Comment by softforge** [comment]
I see you have also created netstreamsmart :+1: 

Do you think using netstreamsmart may help with the close POST not being sent when using RTMPT? Should publishClose() and publishDispose() both send the close POST to the server after the buffer has emptied?

Many thanks

**Comment by jakehilton** [comment]
You can definitely try netstreamsmart to see if it solves your issue. I’ve not experienced the issue you’re reporting aside from the server not being aware the client has gone away. I’ve never had an issue with the client not knowing they had shut down.

I wrote a test to verify the close timing of an rtmpt and it works great client side. I did not however put a publishing stream on it so I’ll have to do more testing around that.

What flash server are you using? AMS or Wowza or Red5?

Thanks

**Comment by softforge** [comment]
Hi Jake, thanks for your comments, I have finally managed to solve this! I am actually using RTMPlite which may have been part of the problem. I changed to using netstreamsmart and didn't close down the net connection straight away after the RTMPT stream had finished. While I didn't see the close POST I was expecting, letting the netstream finish naturally before closing the netconnection did the trick as there must be something to identify the stream has finished within the protocol that is being picked up by RTMPlite.

Thanks for your help and these great libraries!

**Comment by jakehilton** [comment]
RTMPlite uses AMF0 so in your netconnectionsmart params make sure you set the object encoding properly.. I’m sure you have done this but just to double check.. it would be like so:

nc = new NetConnectionSmart();
nc.objectEncoding = ObjectEncoding.AMF0;
…

Glad to hear you got it working though!

**Comment by softforge** [comment]
Thanks Jake, that is very helpful!

**Comment by jakehilton** [comment]
I just wanted to put a note in here that the issue where the POST messages did not stop has been resolved. It was very prevalent when using the library in a port test capacity.

I hope this helps in the scenario where you are using it as well.

**Comment by softforge** [comment]
Thanks very much Jack! :+1: 

We will upgrade the library and give it a test.
