### ISSUE TITLE
NetConnectionSmart.portArray functionality

### ISSUE THREAD

**Issue by mike131** [jakehilton/netconnectionsmart#6]
Hi @jakehilton ,

First, thanks for this awesome class!

I had a quick question about the portArray. I have a bunch of option that I want to check (about 16 configurations).

Does it check them all? or just return success on the first success from the array?

**Comment by jakehilton** [comment]
It depends on how you have the class operate. If you're just using it to connect to a server then it will use the first success it hits. It will try the first items in the array and work down from there. It will not even try the other items after a success.

You can have the class perform a port test using all the items in the declared portArray. It will report back the status of each item to you but will not establish a lasting connection to the endpoint.

I guess you could have it run a port test and then based on the results select a configuration you like and use that. It would take some time to have it negotiate a connection that way however.

I hope that helps.

**Comment by mike131** [comment]
I am just using the class to check ports (different combination of protocols, ports, proxies).

I would like to have it test them all if possible, but would it be running in parallel?

Sorry if my questions are stupid, I am not really too familiar with Flash.

Any example on running multiple configs in parallel?

**Comment by jakehilton** [comment]
If you run it in the port test configuration it will execute the tests in parallel by default.. unless you tell it you want it to test one at a time (sequentially).

So something like this to run a default port test.
```Actionscript
            var ncs:NetConnectionSmart = new NetConnectionSmart();
            ncs.portArray = [443, 80, 1935];
            ncs.port_test = true;
            ncs.addEventListener(NetStatusEvent.NET_STATUS, handleNetStatus);
            ncs.connect("mediaserver.com/application");

            function handleNetStatus(e:NetStatusEvent):void {
                switch (e.info.code) {
                    case NetConnectionSmart.NETCONNECTION_PORT_TEST_UPDATE:
                        var currConnection:PortConnection = e.info.internalTarget as PortConnection;
                        var currType:NetConnectionType = (e.target as NetConnectionSmart).netConnections[currConnection.id];

                        var status_output:String = "";
                        if (currConnection && currConnection.status && currConnection.status.info.code && currConnection.status.info.code != "") {
                            var status_input:String = currConnection.was_connected ? NetConnectionSmart.NETCONNECTION_CONNECT_SUCCESS : currConnection.status.info.code;

                            var proxy_add:String = currConnection.proxyType;
                            status_output = status_input.split('NetConnection.Connect.')[1] + " proxy type ";
                            if (currConnection.was_connected)
                                proxy_add = currConnection.connectedProxyType;

                            status_output += proxy_add;

                            trace(currType.full_protocol.toUpperCase() + " port " + String(currType.port) + " " + status_output);
                        }
                        break;
                    case NetConnectionSmart.NETCONNECTION_PORT_TEST_COMPLETE:
                        trace("we're done");
                        break;
                }
            }
```
Which would output something like this:

[trace] RTMP port 443 Failed proxy type CONNECTOnly
[trace] RTMP port 80 Success proxy type none
[trace] RTMP port 1935 Success proxy type none
[trace] RTMP port 80 Failed proxy type CONNECTOnly
[trace] RTMP port 1935 Failed proxy type CONNECTOnly
[trace] RTMPT port 80 Success proxy type HTTP
[trace] RTMPT port 1935 Success proxy type HTTP
[trace] RTMPT port 443 Failed proxy type best
[trace] RTMP port 443 Failed proxy type none
[trace] we're done

It reports back on the status of each one as soon as it hears back from the endpoint.

No worries on the questions.. always happy to share.

**Comment by mike131** [comment]
Awesome!

Thanks!!
