### ISSUE TITLE
Access which protocol a stream is using

### ISSUE THREAD

**Issue by Joe-Palmer** [jakehilton/netconnectionsmart#8]
Is it possible to determine which protocol a stream is using? We have a workaround (for a bug in Flash) in place for RTMPT streams but we don't want to apply this workaround when the stream is using RTMP.

The workaround applies just as we close the stream so is there a way to determine the protocol that was used at this point using your library?

Many thanks

**Comment by jakehilton** [comment]
You should just have to ask the NetConnectionSmart instance for it's protocol.

Taken from the example on the home page.. you can see where we trace out the protocol the netconnectionsmart is using:

```
var ncs:NetConnectionSmart = new NetConnectionSmart();
ncs.addEventListener(NetStatusEvent.NET_STATUS,function(e:NetStatusEvent):void{
    trace("connection status: "+e.info.code);
    trace(ncs.uri);
    trace(ncs.protocol); //tracing protocol here

    switch (e.info.code){
        case NetConnectionSmart.NETCONNECTION_CONNECT_SUCCESS:
            var ns:NetStream = new NetStream(ncs.connection);
            //do other netstream actions
            break;
    }
});

ncs.connect("rtmp://myserver.com/application");
```

If you're using NetStreamSmart you can get a handle back to the netconnectionsmart that the netstreamsmart is using:

nss is a netstreamsmart object.. simply do the following:
```
var ncs:NetConnectionSmart = nss. netconnection as NetConnectionSmart;
trace(ncs.protocol);
```
I hope that helps for that you're trying to do.

**Comment by Joe-Palmer** [comment]
That's really helpful, thank you so much!

We'll give it a try and report back...
